plugins {
    id 'com.palantir.docker' version '0.36.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'api-user'

docker{
    println(tasks.bootJar.outputs.files) //jar 파일 경로 출력 (디버깅용)
    name "ddarahakit2026/"+rootProject.name + '-' + project.name + ':' + version // 도커 이미지 태그
    dockerfile file('../Dockerfile') //사용할 Dockerfile 경로 지정
    files tasks.bootJar.outputs.files //이미지 빌드에 포함할 파일 지정
    //Dockerfile로 전달할 빌드 인자 지정
    buildArgs(['JAR_FILE': tasks.bootJar.archiveFileName.get()])
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}